from ....pywinauto.script_generator.recorder_defines import *

from ....pywinauto.uia_defines import IUIA

EVENT_ID_EVENT_NAME_MAP = {
    IUIA().UIA_dll.UIA_AsyncContentLoadedEventId: EVENT_ASYNC_CONTENT_LOADED,
    IUIA().UIA_dll.UIA_Drag_DragCancelEventId: EVENT_DRAG_CANCEL,
    IUIA().UIA_dll.UIA_Drag_DragCompleteEventId: EVENT_DRAG_COMPLETE,
    IUIA().UIA_dll.UIA_DropTarget_DroppedEventId: EVENT_DRAG_DROPPED,
    IUIA().UIA_dll.UIA_DropTarget_DragEnterEventId: EVENT_DRAG_ENTER,
    IUIA().UIA_dll.UIA_DropTarget_DragLeaveEventId: EVENT_DRAG_LEAVE,
    IUIA().UIA_dll.UIA_Drag_DragStartEventId: EVENT_DRAG_START,
    IUIA().UIA_dll.UIA_TextEdit_ConversionTargetChangedEventId: EVENT_EDIT_CONVERSION_TARGET_CHANGED,
    IUIA().UIA_dll.UIA_TextEdit_TextChangedEventId: EVENT_EDIT_TEXT_CHANGED,
    IUIA().UIA_dll.UIA_AutomationFocusChangedEventId: EVENT_FOCUS_CHANGED,
    IUIA().UIA_dll.UIA_HostedFragmentRootsInvalidatedEventId: EVENT_HOSTED_FRAGMENT_ROOTS_INVALIDATED,
    IUIA().UIA_dll.UIA_InputDiscardedEventId: EVENT_INPUT_DISCARDED,
    IUIA().UIA_dll.UIA_InputReachedOtherElementEventId: EVENT_INPUT_REACHED_OTHER_ELEMENT,
    IUIA().UIA_dll.UIA_InputReachedTargetEventId: EVENT_INPUT_REACHED_TARGET,
    IUIA().UIA_dll.UIA_Invoke_InvokedEventId: EVENT_INVOKED,
    IUIA().UIA_dll.UIA_LayoutInvalidatedEventId: EVENT_LAYOUT_INVALIDATED,
    IUIA().UIA_dll.UIA_LiveRegionChangedEventId: EVENT_LIVE_REGION_CHANGED,
    IUIA().UIA_dll.UIA_MenuClosedEventId: EVENT_MENU_CLOSED,
    IUIA().UIA_dll.UIA_MenuModeEndEventId: EVENT_MENU_END,
    IUIA().UIA_dll.UIA_MenuOpenedEventId: EVENT_MENU_OPENED,
    IUIA().UIA_dll.UIA_MenuModeStartEventId: EVENT_MENU_START,
    IUIA().UIA_dll.UIA_AutomationPropertyChangedEventId: EVENT_PROPERTY_CHANGED,
    IUIA().UIA_dll.UIA_SelectionItem_ElementAddedToSelectionEventId: EVENT_SELECTION_ELEMENT_ADDED,
    IUIA().UIA_dll.UIA_SelectionItem_ElementRemovedFromSelectionEventId: EVENT_SELECTION_ELEMENT_REMOVED,
    IUIA().UIA_dll.UIA_SelectionItem_ElementSelectedEventId: EVENT_SELECTION_ELEMENT_SELECTED,
    IUIA().UIA_dll.UIA_Selection_InvalidatedEventId: EVENT_SELECTION_INVALIDATED,
    IUIA().UIA_dll.UIA_StructureChangedEventId: EVENT_STRUCTURE_CHANGED,
    IUIA().UIA_dll.UIA_SystemAlertEventId: EVENT_SYSTEM_ALERT,
    IUIA().UIA_dll.UIA_Text_TextChangedEventId: EVENT_TEXT_CHANGED,
    IUIA().UIA_dll.UIA_Text_TextSelectionChangedEventId: EVENT_TEXT_SELECTION_CHANGED,
    IUIA().UIA_dll.UIA_ToolTipClosedEventId: EVENT_TOOLTIP_CLOSED,
    IUIA().UIA_dll.UIA_ToolTipOpenedEventId: EVENT_TOOLTIP_OPENED,
    IUIA().UIA_dll.UIA_Window_WindowClosedEventId: EVENT_WINDOW_CLOSED,
    IUIA().UIA_dll.UIA_Window_WindowOpenedEventId: EVENT_WINDOW_OPENED
}


class PropertyEvent(ApplicationEvent):
    def __init__(self, sender, property_name, new_value):
        super(PropertyEvent, self).__init__(EVENT_PROPERTY_CHANGED, sender)
        self.property_name = property_name
        self.new_value = new_value

    def __repr__(self):
        description = "<PropertyEvent - Change '{}' to '{}' from {} ({}, {})>".format(self.property_name,
                                                                                      self.new_value, self.sender,
                                                                                      self.sender.CachedClassName,
                                                                                      self.sender.CachedName)
        return description


class FocusEvent(ApplicationEvent):
    def __init__(self, sender):
        super(FocusEvent, self).__init__(EVENT_FOCUS_CHANGED, sender)

    def __repr__(self):
        description = "<FocusEvent - Change focus to {} ({}, {})>".format(self.sender,
                                                                          self.sender.CachedClassName,
                                                                          self.sender.CachedName)
        return description


class StructureEvent(ApplicationEvent):
    def __init__(self, sender, change_type, runtime_id):
        super(StructureEvent, self).__init__(EVENT_STRUCTURE_CHANGED, sender)
        self.change_type = change_type
        self.runtime_id = runtime_id

    def __repr__(self):
        description = "<StructureEvent - '{}' from {} ({}, {})>".format(self.change_type, self.sender,
                                                                        self.sender.CachedClassName,
                                                                        self.sender.CachedName)
        return description


"""For research purposes"""

all_uia_properties = {
    'AcceleratorKey': IUIA().UIA_dll.UIA_AcceleratorKeyPropertyId,
    'AccessKey': IUIA().UIA_dll.UIA_AccessKeyPropertyId,
    'AnnotationAnnotationTypeId': IUIA().UIA_dll.UIA_AnnotationAnnotationTypeIdPropertyId,
    'AnnotationAnnotationTypeName': IUIA().UIA_dll.UIA_AnnotationAnnotationTypeNamePropertyId,
    'AnnotationAuthor': IUIA().UIA_dll.UIA_AnnotationAuthorPropertyId,
    'AnnotationDateTime': IUIA().UIA_dll.UIA_AnnotationDateTimePropertyId,
    'AnnotationObjects': IUIA().UIA_dll.UIA_AnnotationObjectsPropertyId,
    'AnnotationTarget': IUIA().UIA_dll.UIA_AnnotationTargetPropertyId,
    'AnnotationTypes': IUIA().UIA_dll.UIA_AnnotationTypesPropertyId,
    'AriaProperties': IUIA().UIA_dll.UIA_AriaPropertiesPropertyId,
    'AriaRole': IUIA().UIA_dll.UIA_AriaRolePropertyId,
    'AutomationId': IUIA().UIA_dll.UIA_AutomationIdPropertyId,
    'BoundingRectangle': IUIA().UIA_dll.UIA_BoundingRectanglePropertyId,
    'ClassName': IUIA().UIA_dll.UIA_ClassNamePropertyId,
    'ClickablePoint': IUIA().UIA_dll.UIA_ClickablePointPropertyId,
    'ControlType': IUIA().UIA_dll.UIA_ControlTypePropertyId,
    'ControllerFor': IUIA().UIA_dll.UIA_ControllerForPropertyId,
    'Culture': IUIA().UIA_dll.UIA_CulturePropertyId,
    'DescribedBy': IUIA().UIA_dll.UIA_DescribedByPropertyId,
    'DockDockPosition': IUIA().UIA_dll.UIA_DockDockPositionPropertyId,
    'DragDropEffect': IUIA().UIA_dll.UIA_DragDropEffectPropertyId,
    'DragDropEffects': IUIA().UIA_dll.UIA_DragDropEffectsPropertyId,
    'DragGrabbedItems': IUIA().UIA_dll.UIA_DragGrabbedItemsPropertyId,
    'DragIsGrabbed': IUIA().UIA_dll.UIA_DragIsGrabbedPropertyId,
    'DropTargetDropTargetEffect': IUIA().UIA_dll.UIA_DropTargetDropTargetEffectPropertyId,
    'DropTargetDropTargetEffects': IUIA().UIA_dll.UIA_DropTargetDropTargetEffectsPropertyId,
    'ExpandCollapseExpandCollapseState': IUIA().UIA_dll.UIA_ExpandCollapseExpandCollapseStatePropertyId,
    'FlowsFrom': IUIA().UIA_dll.UIA_FlowsFromPropertyId,
    'FlowsTo': IUIA().UIA_dll.UIA_FlowsToPropertyId,
    'FrameworkId': IUIA().UIA_dll.UIA_FrameworkIdPropertyId,
    'FullDescription': IUIA().UIA_dll.UIA_FullDescriptionPropertyId,
    'GridColumnCount': IUIA().UIA_dll.UIA_GridColumnCountPropertyId,
    'GridItemColumn': IUIA().UIA_dll.UIA_GridItemColumnPropertyId,
    'GridItemColumnSpan': IUIA().UIA_dll.UIA_GridItemColumnSpanPropertyId,
    'GridItemContainingGrid': IUIA().UIA_dll.UIA_GridItemContainingGridPropertyId,
    'GridItemRow': IUIA().UIA_dll.UIA_GridItemRowPropertyId,
    'GridItemRowSpan': IUIA().UIA_dll.UIA_GridItemRowSpanPropertyId,
    'GridRowCount': IUIA().UIA_dll.UIA_GridRowCountPropertyId,
    'HasKeyboardFocus': IUIA().UIA_dll.UIA_HasKeyboardFocusPropertyId,
    'HelpText': IUIA().UIA_dll.UIA_HelpTextPropertyId,
    'IsAnnotationPatternAvailable': IUIA().UIA_dll.UIA_IsAnnotationPatternAvailablePropertyId,
    'IsContentElement': IUIA().UIA_dll.UIA_IsContentElementPropertyId,
    'IsControlElement': IUIA().UIA_dll.UIA_IsControlElementPropertyId,
    'IsCustomNavigationPatternAvailable': IUIA().UIA_dll.UIA_IsCustomNavigationPatternAvailablePropertyId,
    'IsDataValidForForm': IUIA().UIA_dll.UIA_IsDataValidForFormPropertyId,
    'IsDockPatternAvailable': IUIA().UIA_dll.UIA_IsDockPatternAvailablePropertyId,
    'IsDragPatternAvailable': IUIA().UIA_dll.UIA_IsDragPatternAvailablePropertyId,
    'IsDropTargetPatternAvailable': IUIA().UIA_dll.UIA_IsDropTargetPatternAvailablePropertyId,
    'IsEnabled': IUIA().UIA_dll.UIA_IsEnabledPropertyId,
    'IsExpandCollapsePatternAvailable': IUIA().UIA_dll.UIA_IsExpandCollapsePatternAvailablePropertyId,
    'IsGridItemPatternAvailable': IUIA().UIA_dll.UIA_IsGridItemPatternAvailablePropertyId,
    'IsGridPatternAvailable': IUIA().UIA_dll.UIA_IsGridPatternAvailablePropertyId,
    'IsInvokePatternAvailable': IUIA().UIA_dll.UIA_IsInvokePatternAvailablePropertyId,
    'IsItemContainerPatternAvailable': IUIA().UIA_dll.UIA_IsItemContainerPatternAvailablePropertyId,
    'IsKeyboardFocusable': IUIA().UIA_dll.UIA_IsKeyboardFocusablePropertyId,
    'IsLegacyIAccessiblePatternAvailable': IUIA().UIA_dll.UIA_IsLegacyIAccessiblePatternAvailablePropertyId,
    'IsMultipleViewPatternAvailable': IUIA().UIA_dll.UIA_IsMultipleViewPatternAvailablePropertyId,
    'IsObjectModelPatternAvailable': IUIA().UIA_dll.UIA_IsObjectModelPatternAvailablePropertyId,
    'IsOffscreen': IUIA().UIA_dll.UIA_IsOffscreenPropertyId,
    'IsPassword': IUIA().UIA_dll.UIA_IsPasswordPropertyId,
    'IsPeripheral': IUIA().UIA_dll.UIA_IsPeripheralPropertyId,
    'IsRangeValuePatternAvailable': IUIA().UIA_dll.UIA_IsRangeValuePatternAvailablePropertyId,
    'IsRequiredForForm': IUIA().UIA_dll.UIA_IsRequiredForFormPropertyId,
    'IsScrollItemPatternAvailable': IUIA().UIA_dll.UIA_IsScrollItemPatternAvailablePropertyId,
    'IsScrollPatternAvailable': IUIA().UIA_dll.UIA_IsScrollPatternAvailablePropertyId,
    'IsSelectionItemPatternAvailable': IUIA().UIA_dll.UIA_IsSelectionItemPatternAvailablePropertyId,
    'IsSelectionPatternAvailable': IUIA().UIA_dll.UIA_IsSelectionPatternAvailablePropertyId,
    'IsSpreadsheetItemPatternAvailable': IUIA().UIA_dll.UIA_IsSpreadsheetItemPatternAvailablePropertyId,
    'IsSpreadsheetPatternAvailable': IUIA().UIA_dll.UIA_IsSpreadsheetPatternAvailablePropertyId,
    'IsStylesPatternAvailable': IUIA().UIA_dll.UIA_IsStylesPatternAvailablePropertyId,
    'IsSynchronizedInputPatternAvailable': IUIA().UIA_dll.UIA_IsSynchronizedInputPatternAvailablePropertyId,
    'IsTableItemPatternAvailable': IUIA().UIA_dll.UIA_IsTableItemPatternAvailablePropertyId,
    'IsTablePatternAvailable': IUIA().UIA_dll.UIA_IsTablePatternAvailablePropertyId,
    'IsTextChildPatternAvailable': IUIA().UIA_dll.UIA_IsTextChildPatternAvailablePropertyId,
    'IsTextEditPatternAvailable': IUIA().UIA_dll.UIA_IsTextEditPatternAvailablePropertyId,
    'IsTextPattern2Available': IUIA().UIA_dll.UIA_IsTextPattern2AvailablePropertyId,
    'IsTextPatternAvailable': IUIA().UIA_dll.UIA_IsTextPatternAvailablePropertyId,
    'IsTogglePatternAvailable': IUIA().UIA_dll.UIA_IsTogglePatternAvailablePropertyId,
    'IsTransformPattern2Available': IUIA().UIA_dll.UIA_IsTransformPattern2AvailablePropertyId,
    'IsTransformPatternAvailable': IUIA().UIA_dll.UIA_IsTransformPatternAvailablePropertyId,
    'IsValuePatternAvailable': IUIA().UIA_dll.UIA_IsValuePatternAvailablePropertyId,
    'IsVirtualizedItemPatternAvailable': IUIA().UIA_dll.UIA_IsVirtualizedItemPatternAvailablePropertyId,
    'IsWindowPatternAvailable': IUIA().UIA_dll.UIA_IsWindowPatternAvailablePropertyId,
    'ItemStatus': IUIA().UIA_dll.UIA_ItemStatusPropertyId,
    'ItemType': IUIA().UIA_dll.UIA_ItemTypePropertyId,
    'LabeledBy': IUIA().UIA_dll.UIA_LabeledByPropertyId,
    'LandmarkType': IUIA().UIA_dll.UIA_LandmarkTypePropertyId,
    'LegacyIAccessibleChildId': IUIA().UIA_dll.UIA_LegacyIAccessibleChildIdPropertyId,
    'LegacyIAccessibleDefaultAction': IUIA().UIA_dll.UIA_LegacyIAccessibleDefaultActionPropertyId,
    'LegacyIAccessibleDescription': IUIA().UIA_dll.UIA_LegacyIAccessibleDescriptionPropertyId,
    'LegacyIAccessibleHelp': IUIA().UIA_dll.UIA_LegacyIAccessibleHelpPropertyId,
    'LegacyIAccessibleKeyboardShortcut': IUIA().UIA_dll.UIA_LegacyIAccessibleKeyboardShortcutPropertyId,
    'LegacyIAccessibleName': IUIA().UIA_dll.UIA_LegacyIAccessibleNamePropertyId,
    'LegacyIAccessibleRole': IUIA().UIA_dll.UIA_LegacyIAccessibleRolePropertyId,
    'LegacyIAccessibleSelection': IUIA().UIA_dll.UIA_LegacyIAccessibleSelectionPropertyId,
    'LegacyIAccessibleState': IUIA().UIA_dll.UIA_LegacyIAccessibleStatePropertyId,
    'LegacyIAccessibleValue': IUIA().UIA_dll.UIA_LegacyIAccessibleValuePropertyId,
    'Level': IUIA().UIA_dll.UIA_LevelPropertyId,
    'LiveSetting': IUIA().UIA_dll.UIA_LiveSettingPropertyId,
    'LocalizedControlType': IUIA().UIA_dll.UIA_LocalizedControlTypePropertyId,
    'LocalizedLandmarkType': IUIA().UIA_dll.UIA_LocalizedLandmarkTypePropertyId,
    'MultipleViewCurrentView': IUIA().UIA_dll.UIA_MultipleViewCurrentViewPropertyId,
    'MultipleViewSupportedViews': IUIA().UIA_dll.UIA_MultipleViewSupportedViewsPropertyId,
    'Name': IUIA().UIA_dll.UIA_NamePropertyId,
    'NativeWindowHandle': IUIA().UIA_dll.UIA_NativeWindowHandlePropertyId,
    'OptimizeForVisualContent': IUIA().UIA_dll.UIA_OptimizeForVisualContentPropertyId,
    'Orientation': IUIA().UIA_dll.UIA_OrientationPropertyId,
    'PositionInSet': IUIA().UIA_dll.UIA_PositionInSetPropertyId,
    'ProcessId': IUIA().UIA_dll.UIA_ProcessIdPropertyId,
    'ProviderDescription': IUIA().UIA_dll.UIA_ProviderDescriptionPropertyId,
    'RangeValueIsReadOnly': IUIA().UIA_dll.UIA_RangeValueIsReadOnlyPropertyId,
    'RangeValueLargeChange': IUIA().UIA_dll.UIA_RangeValueLargeChangePropertyId,
    'RangeValueMaximum': IUIA().UIA_dll.UIA_RangeValueMaximumPropertyId,
    'RangeValueMinimum': IUIA().UIA_dll.UIA_RangeValueMinimumPropertyId,
    'RangeValueSmallChange': IUIA().UIA_dll.UIA_RangeValueSmallChangePropertyId,
    'RangeValueValue': IUIA().UIA_dll.UIA_RangeValueValuePropertyId,
    'RuntimeId': IUIA().UIA_dll.UIA_RuntimeIdPropertyId,
    'ScrollHorizontalScrollPercent': IUIA().UIA_dll.UIA_ScrollHorizontalScrollPercentPropertyId,
    'ScrollHorizontalViewSize': IUIA().UIA_dll.UIA_ScrollHorizontalViewSizePropertyId,
    'ScrollHorizontallyScrollable': IUIA().UIA_dll.UIA_ScrollHorizontallyScrollablePropertyId,
    'ScrollVerticalScrollPercent': IUIA().UIA_dll.UIA_ScrollVerticalScrollPercentPropertyId,
    'ScrollVerticalViewSize': IUIA().UIA_dll.UIA_ScrollVerticalViewSizePropertyId,
    'ScrollVerticallyScrollable': IUIA().UIA_dll.UIA_ScrollVerticallyScrollablePropertyId,
    'SelectionCanSelectMultiple': IUIA().UIA_dll.UIA_SelectionCanSelectMultiplePropertyId,
    'SelectionIsSelectionRequired': IUIA().UIA_dll.UIA_SelectionIsSelectionRequiredPropertyId,
    'SelectionItemIsSelected': IUIA().UIA_dll.UIA_SelectionItemIsSelectedPropertyId,
    'SelectionItemSelectionContainer': IUIA().UIA_dll.UIA_SelectionItemSelectionContainerPropertyId,
    'SelectionSelection': IUIA().UIA_dll.UIA_SelectionSelectionPropertyId,
    'SizeOfSet': IUIA().UIA_dll.UIA_SizeOfSetPropertyId,
    'SpreadsheetItemAnnotationObjects': IUIA().UIA_dll.UIA_SpreadsheetItemAnnotationObjectsPropertyId,
    'SpreadsheetItemAnnotationTypes': IUIA().UIA_dll.UIA_SpreadsheetItemAnnotationTypesPropertyId,
    'SpreadsheetItemFormula': IUIA().UIA_dll.UIA_SpreadsheetItemFormulaPropertyId,
    'StylesExtendedProperties': IUIA().UIA_dll.UIA_StylesExtendedPropertiesPropertyId,
    'StylesFillColor': IUIA().UIA_dll.UIA_StylesFillColorPropertyId,
    'StylesFillPatternColor': IUIA().UIA_dll.UIA_StylesFillPatternColorPropertyId,
    'StylesFillPatternStyle': IUIA().UIA_dll.UIA_StylesFillPatternStylePropertyId,
    'StylesShape': IUIA().UIA_dll.UIA_StylesShapePropertyId,
    'StylesStyleId': IUIA().UIA_dll.UIA_StylesStyleIdPropertyId,
    'StylesStyleName': IUIA().UIA_dll.UIA_StylesStyleNamePropertyId,
    'TableColumnHeaders': IUIA().UIA_dll.UIA_TableColumnHeadersPropertyId,
    'TableItemColumnHeaderItems': IUIA().UIA_dll.UIA_TableItemColumnHeaderItemsPropertyId,
    'TableItemRowHeaderItems': IUIA().UIA_dll.UIA_TableItemRowHeaderItemsPropertyId,
    'TableRowHeaders': IUIA().UIA_dll.UIA_TableRowHeadersPropertyId,
    'TableRowOrColumnMajor': IUIA().UIA_dll.UIA_TableRowOrColumnMajorPropertyId,
    'ToggleToggleState': IUIA().UIA_dll.UIA_ToggleToggleStatePropertyId,
    'Transform2CanZoom': IUIA().UIA_dll.UIA_Transform2CanZoomPropertyId,
    'Transform2ZoomLevel': IUIA().UIA_dll.UIA_Transform2ZoomLevelPropertyId,
    'Transform2ZoomMaximum': IUIA().UIA_dll.UIA_Transform2ZoomMaximumPropertyId,
    'Transform2ZoomMinimum': IUIA().UIA_dll.UIA_Transform2ZoomMinimumPropertyId,
    'TransformCanMove': IUIA().UIA_dll.UIA_TransformCanMovePropertyId,
    'TransformCanResize': IUIA().UIA_dll.UIA_TransformCanResizePropertyId,
    'TransformCanRotate': IUIA().UIA_dll.UIA_TransformCanRotatePropertyId,
    'ValueIsReadOnly': IUIA().UIA_dll.UIA_ValueIsReadOnlyPropertyId,
    'ValueValue': IUIA().UIA_dll.UIA_ValueValuePropertyId,
    'WindowCanMaximize': IUIA().UIA_dll.UIA_WindowCanMaximizePropertyId,
    'WindowCanMinimize': IUIA().UIA_dll.UIA_WindowCanMinimizePropertyId,
    'WindowIsModal': IUIA().UIA_dll.UIA_WindowIsModalPropertyId,
    'WindowIsTopmost': IUIA().UIA_dll.UIA_WindowIsTopmostPropertyId,
    'WindowWindowInteractionState': IUIA().UIA_dll.UIA_WindowWindowInteractionStatePropertyId,
    'WindowWindowVisualState': IUIA().UIA_dll.UIA_WindowWindowVisualStatePropertyId,
}
