known_control_types = [
    'Group',
    'Menu',
    'StaticText',
    'Cell',
    'RadioGroup',
    'TextField',
    'SplitGroup',
    'TextArea',
    'ScrollBar',
    'Toolbar',
    'Splitter',
    'ScrollArea',
    'Outline',
    'MenuButton',
    'Column',
    'Button',
    'List',
    'RadioButton',
    'MenuBarItem',
    None,
    'ValueIndicator',
    'Image',
    'DockItem',
    'MenuItem',
    'Table',
    'Row',
    'SystemWide',
    'Window',
    'MenuBar',
    ]

known_top_lvl_control_types = [
    'Window',
    'MenuBar',
    'List',
    'ScrollArea'
]
