name: atspi CI
on:
  push:
    branches: [ "atspi" ]
  pull_request:
    branches: [ "atspi" ]
jobs:
  Linux:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os : [ubuntu-18.04, ubuntu-20.04]
        python: [ '2.7', '3.6', '3.7', '3.8', '3.9', '3.10' ]
        exclude:
          - os: ubuntu-18.04
            python: '3.8'
          - os: ubuntu-18.04
            python: '3.9'
          - os: ubuntu-18.04
            python: '3.10'
          - os: ubuntu-20.04
            python: '2.7'
          - os: ubuntu-20.04
            python: '3.6'
          - os: ubuntu-20.04
            python: '3.7'
    env:
      DISPLAY: ':0'
    steps:
    - name: get repo
      uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get update
        sudo apt upgrade
        sudo apt-get install python3 python3-pip -y
        sudo apt-get install python-xlib
        sudo apt-get install python3-xlib
        sudo apt-get install xsel
        sudo apt install libjavascriptcoregtk-4.0-18
        pip install codecov coverage
        pip install python-xlib --upgrade
        pip install mock --upgrade
        python -m pip install pytest
        sudo apt-get install build-essential libssl-dev
        sudo apt-get install qt5-default
        sudo apt install libxkbcommon-x11-0
        sudo apt install python3-gi gobject-introspection gir1.2-gtk-3.0
        sudo apt-get install at-spi2-core
        sudo apt-get install python3-pyatspi
        sudo apt install -y xvfb x11-utils libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 xdotool
        pip3 install cmake

    - name: Install test apps
      run: |
        git init apps
        cd apps
        git remote add -f origin https://github.com/pywinauto/PywinautoTestapps/
        git config core.sparseCheckout true
        echo "MouseTester/source" >> .git/info/sparse-checkout
        echo "SendKeysTester/source" >> .git/info/sparse-checkout
        git pull origin master
        cd MouseTester/source
        qmake
        make
        chmod a+x mousebuttons
        cp mousebuttons ../
        cd ../..
        cd SendKeysTester/source
        qmake
        make
        chmod a+x send_keys_test_app
        cp send_keys_test_app ../
        export XDG_RUNTIME_DIR=/tmp/runtime-runner
    - name: Remote display start
      run: |
        sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
        sleep 5
        set +eE
        sudo apt install -y gdm3
        sudo service gdm start
        sleep 5
    - name: Run tests
      run: |
        coverage run -m pytest pywinauto/unittests/test_atspi_element_info.py pywinauto/unittests/test_atspi_wrapper.py pywinauto/unittests/test_atspi_controls.py pywinauto/unittests/test_clipboard_linux.py pywinauto/unittests/test_keyboard.py pywinauto/unittests/test_application_linux.py
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
